#ifndef CORE_CONFIG_H
#define CORE_CONFIG_H

#ifndef STR_BUFFER_CAPACITY
	#define STR_BUFFER_CAPACITY (16)
#endif // STR_BUFFER_CAPACITY

#ifndef STR_BUFFER_ALIGNMENT
	#define STR_BUFFER_ALIGNMENT (16)
#endif // STR_BUFFER_ALIGNMENT

#ifndef VEC_BUFFER_CAPACITY
	#define VEC_BUFFER_CAPACITY (16)
#endif // VEC_BUFFER_CAPACITY

#ifndef VEC_BUFFER_ALIGNMENT
	#define VEC_BUFFER_ALIGNMENT (16)
#endif // VEC_BUFFER_ALIGNMENT

#ifndef SET_TABLE_COUNT
	#define SET_TABLE_COUNT (128)
#endif // SET_TABLE_COUNT

#ifndef SET_HASH_VALUE
	#define SET_HASH_VALUE (5381)
#endif // SET_HASH_VALUE

#ifndef SET_LOAD_FACTOR
	#define SET_LOAD_FACTOR (75)
#endif // SET_LOAD_FACTOR

#ifndef MAP_TABLE_COUNT
	#define MAP_TABLE_COUNT (128)
#endif // MAP_TABLE_COUNT

#ifndef MAP_HASH_VALUE
	#define MAP_HASH_VALUE (5381)
#endif // MAP_HASH_VALUE

#ifndef MAP_LOAD_FACTOR
	#define MAP_LOAD_FACTOR (75)
#endif // MAP_LOAD_FACTOR

#ifndef DAT_PAGE_COUNT
	#define DAT_PAGE_COUNT (16)
#endif // DAT_PAGE_COUNT

#ifndef DAT_SPARSE_COUNT
	#define DAT_SPARSE_COUNT (16)
#endif // DAT_SPARSE_COUNT

#ifndef DAT_SPARSE_LIMIT
	#define DAT_SPARSE_LIMIT (16)
#endif // DAT_SPARSE_LIMIT

#ifndef DAT_TOMBSTONE
	#define DAT_TOMBSTONE (0xFFFFFFFFFFFFFFFF)
#endif // DAT_TOMBSTONE

#ifndef ECS_INVALID_ENTITY
	#define ECS_INVALID_ENTITY (0xFFFFFFFFFFFFFFFF)
#endif // ECS_INVALID_ENTITY

#ifndef ECS_MAX_POOL_COUNT
	#define ECS_MAX_POOL_COUNT (0xFFFFFFFFFFFFFFFF)
#endif // ECS_MAX_POOL_COUNT

#ifndef ECS_MAX_POOLS
	#define ECS_MAX_POOLS (64)
#endif // ECS_MAX_POOLS

#endif // CORE_CONFIG_H
